### ISSUE TITLE
Dependências desatualizadas

### ISSUE THREAD

**Issue by gbrabelo** [Escavador/escavador-python#21]
Bom dia!

  Gostaria de solicitar que alterem/atualizem a lista de dependências de pacotes desatualizadas (requests e python-dotenv).
  Adicionalmente seria de valia adicionar ao método de requests o uso de um proxy!

  Muito obrigado.

**Comment by luizcdc** [comment]
Bom dia, @gbrabelo.

Mantemos as versões mínimas das dependências `requests` e `python-dotenv` nos valores atuais por questão de retrocompatibilidade, evitando que os usuários existentes da biblioteca tenham problemas de conflito de dependências. 

Ao instalar a biblioteca com um gerenciador de dependências como o pip, Poetry, pipenv ou conda, o gerenciador tentará instalar a versão mais atualizada possível das dependências que ainda seja compatível com os outros pacotes no seu ambiente de desenvolvimento, portanto é muito raro que essas versões antigas especificadas estejam efetivamente em uso na sua aplicação.

Agradecemos a sua sugestão sobre o suporte integrado para proxies na biblioteca. Recebemos a sugestão e ela já foi registrada no nosso backlog para ser implementada assim que possível.

**Comment by gbrabelo** [comment]
Bom Dia Luiz! Obrigado pela resposta!
A forma como está feita a dependencia -> ^ limita que a biblioteca seja instalada apenas naquela versão.
Ou seja -> python-dotenv fica limitado em >0.19 e <0.20, impossibilitando o uso de bibliotecas mais recentes!

**Comment by luizcdc** [comment]
@gbrabelo, muito obrigado pela correção. Vamos ajustar a sintaxe usada na especificação da versão mínima na próxima atualização.

**Comment by gbrabelo** [comment]
Muito obrigado! Aguardo a atualização!
